### ISSUE TITLE
Bricked E1

### ISSUE THREAD

**Issue by jgjc222** [zvldz/aqcn02_fw#2]
Hi
Thank you for the amazing work!
I think I bricked my hub using:
```
fw_manager.sh -f -m
```
It's safe to assume that there's no feasible way to recover it right?
It's now blinking different colors then it gets stuck on red.

**Comment by zvldz** [comment]
I think this should not have bricked the hub.
This does a factory reset.
And then it goes into test mode. Then, after reboots, hub can most likely be paired with MiHome or Aqara Home, depending on the version hub.

**Comment by jgjc222** [comment]
Thank you for the response!
It doesn't seem to boot or broadcast an access point, and as I mentioned it gives me different colors with every button click, then it gets stuck on red. Any idea what should I do?

**Comment by jgjc222** [comment]
My hub is now working for some reason, thank you! 🙏🏻
